language: node_js
node_js:
  - 7.4.0
before_install:
  - rvm install 2.2.2
  - gem install bundler --no-rdoc --no-ri
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
    condition: "-d build"
install:
  - git fetch origin gh-pages:gh-pages
  - npm install
  - bundle install --deployment
script: bin/travis.sh
